Add auth complete support for Klarna
harendrakr/killbill-adyen-plugin pull request #1
Opened 2020-03-18 19:28 UTC by harendrakr

2020-04-07 08:33 UTC, ducktales commented on src/main/java/org/killbill/billing/plugin/adyen/client/model/PaymentInfo.java
> +        return false;
what is the use of this function if we are just returning false

2020-04-09 11:09 UTC, ducktales commented on src/main/java/org/killbill/billing/plugin/adyen/client/payment/service/AdyenPaymentServiceProviderPort.java
> +            new PurchaseResult(PaymentServiceProviderResult.valueOf("error"),
Can we add log here also?

2020-04-09 11:10 UTC, ducktales commented on src/main/java/org/killbill/billing/plugin/adyen/client/payment/service/AdyenPaymentServiceProviderPort.java
> +        catch (ApiException ex) {
why can't we use single exception to catch the error?

2020-04-13 07:00 UTC, harendrakr commented on src/main/java/org/killbill/billing/plugin/adyen/client/model/PaymentInfo.java
> +        return false;
This was supposed to be default implementation in base class. Derived class implements that. Removing from here as it is Klarna specific.

2020-04-13 07:00 UTC, harendrakr commented on src/main/java/org/killbill/billing/plugin/adyen/client/payment/service/AdyenPaymentServiceProviderPort.java
> +        catch (ApiException ex) {
Both are different types of exception. ApiException has more details compared to IOException.

2020-04-15 09:58 UTC, anchal180591 requested changes

2020-04-15 09:58 UTC, anchal180591 commented on src/main/java/org/killbill/billing/plugin/adyen/client/model/PaymentInfo.java
> +        updateAuthResponse();
Did you override this function `updateAuthResponse` ??

2020-04-15 09:58 UTC, anchal180591 commented on src/main/java/org/killbill/billing/plugin/adyen/client/model/PaymentInfo.java
> +    protected void updateAuthResponse() {}
Why not make this function abstract, if it is not doing anything ?

2020-04-15 09:58 UTC, anchal180591 commented on src/main/java/org/killbill/billing/plugin/adyen/client/model/paymentinfo/KlarnaPaymentInfo.java
> +                logger.warn("Failed to retrieve details keys: " + ex.getMessage());
This is very specific to Klarna, can we add that detail in the log to avoid confusion.

2020-04-15 09:58 UTC, anchal180591 commented on src/main/java/org/killbill/billing/plugin/adyen/client/model/paymentinfo/KlarnaPaymentInfo.java
> +    public void setDetailsData(Map<String, String> detailsData) { this.detailsData = detailsData; }
Why there is no new line gap between two functions ?

2020-04-15 09:58 UTC, anchal180591 commented on src/main/java/org/killbill/billing/plugin/adyen/client/model/paymentinfo/KlarnaPaymentInfo.java
> +    public void setPaymentsData(String paymentsData) { this.paymentsData = paymentsData; }
Why there is no new line gap between two functions ?

2020-04-20 05:17 UTC, merged